import React, { useMemo, useState } from 'react'
import { Canvas } from '@react-three/fiber'
import { Float, OrbitControls } from '@react-three/drei'
import { Search, ShoppingBag, Heart, Menu, X, Minus, Plus, ArrowRight, Check, ChevronDown, SlidersHorizontal } from 'lucide-react'
import './styles.css'

const products = [
 ['The Executive Double-Breasted','Suits',120,'product-1.jpg'],['Midnight Tailored Set','Suits',135,'product-2.jpg'],['Stone Linen Blazer','Blazers',85,'product-3.jpg'],['Ivory Dinner Jacket','Blazers',95,'product-4.jpg'],
 ['Oxford Heritage Shirt','Shirts',42,'product-5.jpg'],['Riviera Knit Polo','Knitwear',48,'product-6.jpg'],['Monochrome City Coat','Outerwear',110,'product-7.jpg'],['Weekend Utility Jacket','Outerwear',78,'product-8.jpg'],
 ['Tobacco Club Blazer','Blazers',92,'product-9.jpg'],['Modern Black Tuxedo','Suits',145,'product-10.jpg'],['Sand Resort Shirt','Shirts',46,'product-11.jpg'],['Slate Business Suit','Suits',130,'product-12.jpg'],
 ['Cream Cable Knit','Knitwear',54,'product-13.jpg'],['Signature Navy Suit','Suits',125,'product-14.jpg'],['Café Suede Jacket','Outerwear',105,'product-15.jpg'],['Essential White Shirt','Shirts',39,'product-16.jpg']
].map((p,i)=>({id:i+1,name:p[0],category:p[1],price:p[2],image:`/products/${p[3]}`,tag:i<3?'New':'',sizes:['S','M','L','XL']}))
const money=n=>`US$${n.toFixed(2)}`

function Sculpture(){return <Canvas camera={{position:[0,0,6.4],fov:40}} dpr={[1,1.75]}><ambientLight intensity={1.8}/><directionalLight position={[4,5,6]} intensity={2.4}/><Float speed={1.25} rotationIntensity={.35} floatIntensity={.35}><mesh rotation={[.35,.65,.15]} scale={.92}><torusKnotGeometry args={[1,.25,180,24]}/><meshStandardMaterial color="#d5d0c7" roughness={.42} metalness={.04}/></mesh></Float><OrbitControls enableZoom={false} enablePan={false} enableDamping autoRotate autoRotateSpeed={.65}/></Canvas>}

export default function App(){
 const [query,setQuery]=useState(''),[cat,setCat]=useState('All'),[sort,setSort]=useState('Featured'),[cart,setCart]=useState([]),[wish,setWish]=useState([]),[drawer,setDrawer]=useState(false),[checkout,setCheckout]=useState(false),[paid,setPaid]=useState(false),[filters,setFilters]=useState(false)
 const shown=useMemo(()=>{let a=products.filter(p=>(cat==='All'||p.category===cat)&&p.name.toLowerCase().includes(query.toLowerCase())); if(sort==='Price low')a.sort((x,y)=>x.price-y.price);if(sort==='Price high')a.sort((x,y)=>y.price-x.price);return a},[query,cat,sort])
 const qty=cart.reduce((s,x)=>s+x.qty,0),total=cart.reduce((s,x)=>s+x.price*x.qty,0)
 const add=p=>{setCart(c=>{let x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]});setDrawer(true)}
 const update=(id,d)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:x.qty+d}:x).filter(x=>x.qty>0))
 const finish=e=>{e.preventDefault();setTimeout(()=>setPaid(true),650)}
 return <div className="app">
  <div className="topbar">Complimentary delivery in Harare on orders over US$80 <span>•</span> Call/WhatsApp +263 77 000 0000</div>
  <header><button className="icon"><Menu/></button><a className="logo" href="#">MW<span>°</span></a><nav><a href="#collection">New arrivals</a><a href="#collection">Collection</a><a href="#story">Our story</a></nav><div className="head-actions"><button className="icon"><Search/></button><button className="icon" onClick={()=>setDrawer(true)}><ShoppingBag/><b>{qty}</b></button></div></header>
  <main>
   <section className="hero"><div className="hero-copy"><p className="eyebrow">HARARE · EST. 2026</p><h1>Quiet confidence,<br/><em>well tailored.</em></h1><p>Modern menswear, selected for the rhythm of Zimbabwean life—from boardroom mornings to late nights in the city.</p><a href="#collection" className="cta">Shop the collection <ArrowRight/></a></div><div className="scene"><Sculpture/><span>Drag to explore</span></div><div className="hero-index">01 / 04</div></section>
   <section className="statement" id="story"><p>THE NEW STANDARD</p><h2>Pieces that speak softly<br/>and stay remembered.</h2></section>
   <section id="collection" className="shop"><div className="shop-head"><div><p className="eyebrow">CURATED FOR NOW</p><h2>The collection</h2></div><p>{shown.length} pieces</p></div>
    <div className="toolbar"><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the collection"/></div><button className="filter-toggle" onClick={()=>setFilters(!filters)}><SlidersHorizontal/> Filters</button><label>Sort <select value={sort} onChange={e=>setSort(e.target.value)}><option>Featured</option><option>Price low</option><option>Price high</option></select><ChevronDown/></label></div>
    <div className="catalog"><aside className={filters?'open':''}><div className="aside-title">Categories <button onClick={()=>setCat('All')}>Reset</button></div>{['All','Suits','Blazers','Shirts','Knitwear','Outerwear'].map(c=><button className={cat===c?'active':''} onClick={()=>{setCat(c);setFilters(false)}} key={c}><span>{c}</span><small>{c==='All'?products.length:products.filter(p=>p.category===c).length}</small></button>)}<div className="aside-note"><b>Made to fit.</b><p>Need sizing help? Chat with our Harare styling desk.</p></div></aside>
     <div className="grid">{shown.map(p=><article key={p.id}><div className="photo">{p.tag&&<span className="tag">{p.tag}</span>}<img src={p.image} alt={p.name}/><button className={wish.includes(p.id)?'liked':''} onClick={()=>setWish(w=>w.includes(p.id)?w.filter(x=>x!==p.id):[...w,p.id])}><Heart fill={wish.includes(p.id)?'currentColor':'none'}/></button></div><div className="meta"><p>{p.category}</p><h3>{p.name}</h3><div><strong>{money(p.price)}</strong><button onClick={()=>add(p)}>Add <Plus/></button></div></div></article>)}</div>
    </div>
   </section>
   <section className="service"><div><span>01</span><h3>Local delivery</h3><p>Same-day options across Harare and secure nationwide delivery.</p></div><div><span>02</span><h3>Easy exchanges</h3><p>Exchange unworn pieces within 14 days of delivery.</p></div><div><span>03</span><h3>Personal styling</h3><p>Book a complimentary sizing and styling consultation.</p></div></section>
  </main>
  <footer><a className="logo">MW<span>°</span></a><p>Modern menswear. Harare, Zimbabwe.</p><div><a>Instagram</a><a>WhatsApp</a><a>Delivery</a><a>Returns</a></div><small>© 2026 MW Atelier. Demo storefront.</small></footer>
  {drawer&&<><div className="shade" onClick={()=>setDrawer(false)}/><aside className="cart"><div className="cart-head"><h2>Your bag <span>({qty})</span></h2><button onClick={()=>setDrawer(false)}><X/></button></div>{!cart.length?<div className="empty"><ShoppingBag/><h3>Your bag is empty</h3><button onClick={()=>setDrawer(false)}>Explore collection</button></div>:<><div className="cart-items">{cart.map(x=><div className="cart-row" key={x.id}><img src={x.image}/><div><p>{x.category}</p><h3>{x.name}</h3><strong>{money(x.price)}</strong><div className="stepper"><button onClick={()=>update(x.id,-1)}><Minus/></button><span>{x.qty}</span><button onClick={()=>update(x.id,1)}><Plus/></button></div></div></div>)}</div><div className="cart-foot"><div><span>Subtotal</span><strong>{money(total)}</strong></div><small>Delivery calculated at checkout</small><button className="checkout" onClick={()=>{setDrawer(false);setCheckout(true)}}>Checkout <ArrowRight/></button></div></>}</aside></>}
  {checkout&&<div className="modal"><div className="checkout-box"><button className="modal-x" onClick={()=>{setCheckout(false);setPaid(false)}}><X/></button>{paid?<div className="success"><div><Check/></div><p className="eyebrow">ORDER RECEIVED</p><h2>Thank you.</h2><p>Your demo order <b>#MW{Math.floor(Math.random()*9000+1000)}</b> has been placed. No payment was processed.</p><button onClick={()=>{setCheckout(false);setPaid(false);setCart([])}}>Continue shopping</button></div>:<form onSubmit={finish}><p className="eyebrow">SECURE CHECKOUT · DEMO</p><h2>Complete your order</h2><div className="notice">Demo payment only — no real charge will be made.</div><div className="form-grid"><label>Full name<input required placeholder="Your full name"/></label><label>Mobile number<input required placeholder="+263 7..."/></label><label>Email address<input required type="email" placeholder="you@example.com"/></label><label>City<select><option>Harare</option><option>Bulawayo</option><option>Mutare</option><option>Gweru</option><option>Other</option></select></label></div><label>Delivery address<textarea required placeholder="Street address, suburb and delivery notes"/></label><fieldset><legend>Payment method</legend>{[['EcoCash','Pay via EcoCash mobile money'],['InnBucks','Pay from your InnBucks wallet'],['OneMoney','Pay via OneMoney'],['Card','Visa or Mastercard (demo)'],['Cash','Cash on delivery — Harare only']].map((x,i)=><label className="pay" key={x[0]}><input type="radio" name="pay" defaultChecked={!i}/><span><b>{x[0]}</b><small>{x[1]}</small></span></label>)}</fieldset><div className="order-total"><span>Order total</span><strong>{money(total)}</strong></div><button className="pay-btn">Place demo order <ArrowRight/></button></form>}</div></div>}
 </div>
}
